### ISSUE TITLE
Won't accept electron beta version

### ISSUE THREAD

**Issue by xxlbug** [hsz/idea-nodesecurity#6]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet

### Description

There is an advisory for electron out, see here https://nodesecurity.io/advisories/563

Vulnerable:< 1.6.16 || >=1.7 <1.7.11 || >= 1.8 <1.8.2-beta.4
Patched:>=1.6.16 <1.7.0|| >=1.7.11 > 1.8.0 || >=1.8.2-beta.4

Currently only a 1.8 beta version is patched for this, see here https://electronjs.org/blog/protocol-handler-fix

If I install the correct version i can't get rid of the "Vulnerable dependency found" message for my package.json:

`"electron": "~1.8.2-beta.5",`

If i had to guess, I would think that your version parsing algorithm doesn't process these beta version schemes right.

### Versions

**Plugin:** 

```
0.3.0
```

**IDE:** 

```
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 29, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
```

**Comment by hsz** [comment]
@xxlbug Thank you for this report!

This issue was present because in `v0.3.0` only `pakcage.json` was analysed.

Since the `v0.4.0` also `package-lock.json` and `yarn.lock` are taken in count and this issue is solved out of the box:

![image](https://user-images.githubusercontent.com/108333/36968185-114b3e08-2062-11e8-815e-f173932d13d2.png)

v0.4.0 should be available in JetBrains repository soon.

**Comment by xxlbug** [comment]
Thank you for the very quick release, works for me 👍
